# Generated by Django 2.1.14 on 2019-11-15 13:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190128_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', max_length=65, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], help_text='Add additional text', required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', required=True))]))], blank=True, null=True),
        ),
    ]
